# Generated by Django 6.1 on 2026-08-28 03:51

import django.db.models.deletion
import typing
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified at"
                    ),
                ),
                (
                    "identity_type",
                    models.CharField(
                        default="user", max_length=32, verbose_name="identity type"
                    ),
                ),
                (
                    "identity_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="identity key"
                    ),
                ),
                (
                    "identity_label",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="identity label"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="is staff"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="is superuser"),
                ),
                (
                    "group_names",
                    models.JSONField(
                        blank=True, default=list, verbose_name="group names"
                    ),
                ),
                (
                    "permission_keys",
                    models.JSONField(
                        blank=True, default=list, verbose_name="permission keys"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="metadata"),
                ),
                ("department", models.CharField(blank=True, max_length=64)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
                "abstract": False,
                "swappable": "STATE_MACHINES_IDENTITY_MODEL",
                "indexes": [
                    models.Index(
                        fields=["identity_type", "identity_key"],
                        name="swapped_org_identit_a5b02a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganizationScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified at"
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[("global", "Global"), ("scoped", "Scoped")],
                        default="global",
                        max_length=20,
                        verbose_name="scope type",
                    ),
                ),
                (
                    "scope_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="scope key",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=255, verbose_name="label"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="state_machine_scopes",
                        to="swapped.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("scope_type", "scope_key"),
                "abstract": False,
                "swappable": "STATE_MACHINES_SCOPE_MODEL",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("organization__isnull", True), ("scope_type", "global")
                            ),
                            models.Q(
                                models.Q(("scope_type", "global"), _negated=True),
                                ("organization__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="swapped_scope_type_and_organization_agree",
                    ),
                    models.UniqueConstraint(
                        fields=("scope_type", "scope_key"),
                        name="swapped_scope_unique_key_per_type",
                    ),
                ],
            },
            bases=(models.Model, typing.Generic),
        ),
    ]
