# Generated by Django 6.1 on 2026-08-24 13:36

import vinta_state_machines.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("state_machines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Risk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("amount", models.IntegerField(default=0)),
                ("owner_id", models.IntegerField(blank=True, null=True)),
                (
                    "status_key",
                    vinta_state_machines.fields.StatusKeyField(
                        blank=True,
                        db_index=True,
                        default="",
                        machine="risk.status",
                        max_length=100,
                    ),
                ),
                (
                    "status_machine_version",
                    vinta_state_machines.fields.StateMachineVersionField(
                        blank=True,
                        help_text="Pinned at creation; publishing a new version never migrates this row.",
                        null=True,
                        related_name="+",
                    ),
                ),
            ],
            bases=(vinta_state_machines.fields.StateMachineMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Roadmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "status_key",
                    vinta_state_machines.fields.StatusKeyField(
                        blank=True,
                        db_index=True,
                        default="",
                        machine="roadmap.status",
                        max_length=100,
                    ),
                ),
                (
                    "engagement_status_key",
                    vinta_state_machines.fields.StatusKeyField(
                        blank=True,
                        db_index=True,
                        default="",
                        machine="roadmap.engagement_status",
                        max_length=100,
                        version_field="engagement_machine_version",
                    ),
                ),
                (
                    "engagement_machine_version",
                    vinta_state_machines.fields.StateMachineVersionField(
                        blank=True,
                        help_text="Pinned at creation; publishing a new version never migrates this row.",
                        null=True,
                        related_name="+",
                    ),
                ),
                (
                    "status_machine_version",
                    vinta_state_machines.fields.StateMachineVersionField(
                        blank=True,
                        help_text="Pinned at creation; publishing a new version never migrates this row.",
                        null=True,
                        related_name="+",
                    ),
                ),
            ],
            bases=(vinta_state_machines.fields.StateMachineMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Unpinned",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_key",
                    vinta_state_machines.fields.StatusKeyField(
                        autopin=False,
                        blank=True,
                        db_index=True,
                        default="",
                        machine="risk.status",
                        max_length=100,
                    ),
                ),
                (
                    "status_machine_version",
                    vinta_state_machines.fields.StateMachineVersionField(
                        blank=True,
                        help_text="Pinned at creation; publishing a new version never migrates this row.",
                        null=True,
                        related_name="+",
                    ),
                ),
            ],
        ),
    ]
