# Generated by Django 5.2.17 on 2026-09-02 21:44

import django.db.models.deletion
import vinta_state_machines.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("state_machines", "0002_status_batch"),
        ("testapp", "0001_initial"),
        migrations.swappable_dependency(settings.STATE_MACHINES_BATCH_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.CharField(blank=True, max_length=200)),
                (
                    "batch_reported_at",
                    vinta_state_machines.fields.BatchReportedAtField(
                        blank=True,
                        editable=False,
                        help_text="Set when the batch counts this record; cleared if it un-counts it.",
                        null=True,
                    ),
                ),
                (
                    "batch",
                    vinta_state_machines.fields.StatusBatchField(
                        blank=True,
                        help_text="Set when the child is created. Cleared by nothing; the stamp does the work.",
                        null=True,
                        related_name="%(app_label)s_%(class)s_members",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                (
                    "status_key",
                    vinta_state_machines.fields.StatusKeyField(
                        blank=True,
                        db_index=True,
                        default="",
                        machine="import_run.status",
                        max_length=100,
                    ),
                ),
                (
                    "status_machine_version",
                    vinta_state_machines.fields.StateMachineVersionField(
                        blank=True,
                        help_text="Pinned at creation; publishing a new version never migrates this row.",
                        null=True,
                        related_name="+",
                    ),
                ),
            ],
            bases=(vinta_state_machines.fields.StateMachineMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                (
                    "batch_reported_at",
                    vinta_state_machines.fields.BatchReportedAtField(
                        blank=True,
                        editable=False,
                        help_text="Set when the batch counts this record; cleared if it un-counts it.",
                        null=True,
                    ),
                ),
                (
                    "status_key",
                    vinta_state_machines.fields.StatusKeyField(
                        blank=True,
                        db_index=True,
                        default="",
                        machine="import_row.status",
                        max_length=100,
                    ),
                ),
                (
                    "batch",
                    vinta_state_machines.fields.StatusBatchField(
                        blank=True,
                        help_text="Set when the child is created. Cleared by nothing; the stamp does the work.",
                        null=True,
                        related_name="%(app_label)s_%(class)s_members",
                    ),
                ),
                (
                    "status_machine_version",
                    vinta_state_machines.fields.StateMachineVersionField(
                        blank=True,
                        help_text="Pinned at creation; publishing a new version never migrates this row.",
                        null=True,
                        related_name="+",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="testapp.importrun",
                    ),
                ),
            ],
            bases=(vinta_state_machines.fields.StateMachineMixin, models.Model),
        ),
        migrations.CreateModel(
            name="RenamedBatchChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etl_counted_at",
                    vinta_state_machines.fields.BatchReportedAtField(
                        blank=True,
                        editable=False,
                        help_text="Set when the batch counts this record; cleared if it un-counts it.",
                        null=True,
                    ),
                ),
                (
                    "etl",
                    vinta_state_machines.fields.StatusBatchField(
                        blank=True,
                        help_text="Set when the child is created. Cleared by nothing; the stamp does the work.",
                        null=True,
                        related_name="%(app_label)s_%(class)s_members",
                        reported_at_field="etl_counted_at",
                    ),
                ),
            ],
        ),
    ]
