# Generated by Django 6.1 on 2026-08-24 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, db_index=True, verbose_name="modified at"),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Stable key, e.g. 'finding.accept' or 'policy.publish'.",
                        max_length=150,
                        unique=True,
                        verbose_name="key",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Optional grouping, e.g. 'compliance', 'billing', 'identity'.",
                        max_length=100,
                        verbose_name="domain",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "action type",
                "verbose_name_plural": "action types",
                "ordering": ("domain", "key"),
            },
        ),
        migrations.CreateModel(
            name="StateMachineState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, db_index=True, verbose_name="modified at"),
                ),
                (
                    "is_initial",
                    models.BooleanField(
                        default=False,
                        help_text="A valid starting state for a new record.",
                        verbose_name="is initial",
                    ),
                ),
                (
                    "is_terminal",
                    models.BooleanField(
                        default=False,
                        help_text="No outgoing transitions are allowed from this state.",
                        verbose_name="is terminal",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("neutral", "Neutral"),
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("danger", "Danger"),
                            ("muted", "Muted"),
                        ],
                        default="neutral",
                        max_length=20,
                        verbose_name="color",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "x",
                    models.IntegerField(
                        default=0,
                        help_text="Horizontal position on the version's canvas. Presentation only.",
                        verbose_name="x",
                    ),
                ),
                (
                    "y",
                    models.IntegerField(
                        default=0,
                        help_text="Vertical position on the version's canvas. Presentation only.",
                        verbose_name="y",
                    ),
                ),
            ],
            options={
                "verbose_name": "state machine state",
                "verbose_name_plural": "state machine states",
                "ordering": ("state_machine_version", "order", "pk"),
            },
        ),
        migrations.CreateModel(
            name="StateMachine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, db_index=True, verbose_name="modified at"),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Stable key referenced from model fields, e.g. 'risk.status'.",
                        max_length=150,
                        unique=True,
                        verbose_name="key",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="entity type"
                    ),
                ),
                (
                    "status_field",
                    models.CharField(
                        default="status", max_length=100, verbose_name="status field"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_state_machines",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
            ],
            options={
                "verbose_name": "state machine",
                "verbose_name_plural": "state machines",
                "ordering": ("key",),
            },
        ),
        migrations.CreateModel(
            name="StateMachineVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, db_index=True, verbose_name="modified at"),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Label pinned by records, e.g. '1', '2024.1', 'v3'.",
                        max_length=50,
                        verbose_name="version",
                    ),
                ),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="lifecycle",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="published at"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_state_machine_versions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "state_machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="state_machines.statemachine",
                        verbose_name="state machine",
                    ),
                ),
            ],
            options={
                "verbose_name": "state machine version",
                "verbose_name_plural": "state machine versions",
                "ordering": ("state_machine__key", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="StateMachineTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, db_index=True, verbose_name="modified at"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Identifies this edge among the ones leaving the same state, e.g. 'approve' or 'approve_over_limit'. Unique per source state.",
                        max_length=200,
                        verbose_name="name",
                    ),
                ),
                (
                    "guard",
                    models.TextField(
                        blank=True,
                        help_text="Optional boolean expression that must hold, e.g. 'obj.amount <= 1000'. A leading '@' names a guard registered with @register_guard.",
                        verbose_name="guard",
                    ),
                ),
                (
                    "required_permission",
                    models.CharField(
                        blank=True,
                        help_text="Optional permission the acting principal must hold.",
                        max_length=200,
                        verbose_name="required permission",
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False,
                        help_text="The transition needs an explicit approval to commit.",
                        verbose_name="requires approval",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Decides which edge wins when several leave the same state under the same action: the first one whose guard holds.",
                        verbose_name="order",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "action_type",
                    models.ForeignKey(
                        help_text="The event from the shared vocabulary that triggers this edge.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transitions",
                        to="state_machines.actiontype",
                        verbose_name="action type",
                    ),
                ),
                (
                    "from_state",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null means creation: the edge into an initial state.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transitions",
                        to="state_machines.statemachinestate",
                        verbose_name="from state",
                    ),
                ),
                (
                    "to_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transitions",
                        to="state_machines.statemachinestate",
                        verbose_name="to state",
                    ),
                ),
                (
                    "state_machine_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="state_machines.statemachineversion",
                        verbose_name="state machine version",
                    ),
                ),
            ],
            options={
                "verbose_name": "state machine transition",
                "verbose_name_plural": "state machine transitions",
                "ordering": (
                    "state_machine_version",
                    "from_state__order",
                    "order",
                    "pk",
                ),
            },
        ),
        migrations.AddField(
            model_name="statemachinestate",
            name="state_machine_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="states",
                to="state_machines.statemachineversion",
                verbose_name="state machine version",
            ),
        ),
        migrations.CreateModel(
            name="StateMachineHook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, db_index=True, verbose_name="modified at"),
                ),
                (
                    "handler_key",
                    models.CharField(
                        db_index=True,
                        help_text="Key of a function registered with @register_side_effect.",
                        max_length=150,
                        verbose_name="handler key",
                    ),
                ),
                (
                    "timing",
                    models.CharField(
                        choices=[("before", "Before"), ("after", "After")],
                        default="after",
                        max_length=10,
                        verbose_name="timing",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("transition", "A specific transition"),
                            ("any_transition", "Any transition of the version"),
                            ("enter_state", "Entering a specific state"),
                            ("leave_state", "Leaving a specific state"),
                        ],
                        default="transition",
                        max_length=20,
                        verbose_name="event",
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON parameter for this handler on this binding, stored on the relationship and handed to the function as context.params.",
                        verbose_name="params",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "on_commit",
                    models.BooleanField(
                        default=False,
                        help_text="Defer an 'after' hook until the surrounding transaction commits. Ignored for 'before' hooks.",
                        verbose_name="on commit",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required when the event is 'enter_state' or 'leave_state'.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hooks",
                        to="state_machines.statemachinestate",
                        verbose_name="state",
                    ),
                ),
                (
                    "transition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required when the event is 'transition'.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hooks",
                        to="state_machines.statemachinetransition",
                        verbose_name="transition",
                    ),
                ),
                (
                    "state_machine_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hooks",
                        to="state_machines.statemachineversion",
                        verbose_name="state machine version",
                    ),
                ),
            ],
            options={
                "verbose_name": "state machine hook",
                "verbose_name_plural": "state machine hooks",
                "ordering": ("state_machine_version", "timing", "order", "pk"),
            },
        ),
        migrations.AddField(
            model_name="statemachine",
            name="default_version",
            field=models.ForeignKey(
                blank=True,
                help_text="The version new records pin. Publishing never migrates old rows.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for",
                to="state_machines.statemachineversion",
                verbose_name="default version",
            ),
        ),
        migrations.CreateModel(
            name="StatusDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, db_index=True, verbose_name="modified at"),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True,
                        help_text="Which entity this status belongs to, e.g. 'risk' or 'invoice'.",
                        max_length=100,
                        verbose_name="entity type",
                    ),
                ),
                (
                    "status_field",
                    models.CharField(
                        default="status",
                        help_text="Column this vocabulary governs, e.g. 'status', 'engagement_status'.",
                        max_length=100,
                        verbose_name="status field",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Stable key, unique per (entity type, status field).",
                        max_length=100,
                        verbose_name="key",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "status definition",
                "verbose_name_plural": "status definitions",
                "ordering": ("entity_type", "status_field", "key"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity_type", "status_field", "key"),
                        name="statusdefinition_unique_key_per_field",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="statemachinestate",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bound_states",
                to="state_machines.statusdefinition",
                verbose_name="status",
            ),
        ),
        migrations.CreateModel(
            name="StatusTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, db_index=True, verbose_name="modified at"),
                ),
                (
                    "target_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="target id"
                    ),
                ),
                (
                    "status_field",
                    models.CharField(
                        default="status",
                        help_text="Which status column changed, for entities that have more than one.",
                        max_length=100,
                        verbose_name="status field",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="comment")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="metadata"),
                ),
                (
                    "action_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="status_transitions",
                        to="state_machines.actiontype",
                        verbose_name="action type",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null means the change was made by the system.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_transitions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actor",
                    ),
                ),
                (
                    "from_status",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null on the first transition of a record.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transitions_out",
                        to="state_machines.statusdefinition",
                        verbose_name="from status",
                    ),
                ),
                (
                    "state_machine_version",
                    models.ForeignKey(
                        help_text="The version that authorized this edge.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authorized_transitions",
                        to="state_machines.statemachineversion",
                        verbose_name="state machine version",
                    ),
                ),
                (
                    "target_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_transitions",
                        to="contenttypes.contenttype",
                        verbose_name="target type",
                    ),
                ),
                (
                    "to_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transitions_in",
                        to="state_machines.statusdefinition",
                        verbose_name="to status",
                    ),
                ),
                (
                    "transition",
                    models.ForeignKey(
                        blank=True,
                        help_text="The exact edge that was taken. One action may name several edges between the same pair of states, so the action alone does not identify the move.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="status_transitions",
                        to="state_machines.statemachinetransition",
                        verbose_name="transition",
                    ),
                ),
            ],
            options={
                "verbose_name": "status transition",
                "verbose_name_plural": "status transitions",
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.AddConstraint(
            model_name="statemachineversion",
            constraint=models.UniqueConstraint(
                fields=("state_machine", "version"),
                name="statemachineversion_unique_label",
            ),
        ),
        migrations.AddConstraint(
            model_name="statemachineversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("lifecycle", "draft"), ("published_at__isnull", True)),
                    models.Q(("lifecycle", "draft"), _negated=True),
                    _connector="OR",
                ),
                name="statemachineversion_draft_has_no_published_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="statemachinetransition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("from_state__isnull", False)),
                fields=("state_machine_version", "from_state", "name"),
                name="statemachinetransition_unique_name_per_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="statemachinetransition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("from_state__isnull", True)),
                fields=("state_machine_version", "name"),
                name="statemachinetransition_unique_creation_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="statemachinehook",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("event", "transition"),
                        ("state__isnull", True),
                        ("transition__isnull", False),
                    ),
                    models.Q(
                        ("event", "any_transition"),
                        ("state__isnull", True),
                        ("transition__isnull", True),
                    ),
                    models.Q(
                        ("event__in", ("enter_state", "leave_state")),
                        ("state__isnull", False),
                        ("transition__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="statemachinehook_target_matches_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="statemachine",
            constraint=models.UniqueConstraint(
                fields=("entity_type", "status_field"),
                name="statemachine_one_per_entity_field",
            ),
        ),
        migrations.AddConstraint(
            model_name="statemachinestate",
            constraint=models.UniqueConstraint(
                fields=("state_machine_version", "status"),
                name="statemachinestate_unique_status_per_version",
            ),
        ),
        migrations.AddIndex(
            model_name="statustransition",
            index=models.Index(
                fields=["target_type", "target_id", "status_field", "-created_at"],
                name="statustransition_target_idx",
            ),
        ),
    ]
