# Generated by Django 5.2.17 on 2026-09-02 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("state_machines", "0001_initial"),
        # Same reasoning as 0001: the batch's actor and the report's batch are declared
        # against swappable settings, and the autodetector records no edge because
        # unswapped both models are local. Swapped, the edge is real.
        migrations.swappable_dependency(settings.STATE_MACHINES_IDENTITY_MODEL),
        migrations.swappable_dependency(settings.STATE_MACHINES_BATCH_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified at"
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="target id"
                    ),
                ),
                (
                    "status_field",
                    models.CharField(
                        default="status",
                        help_text="Which status column is waiting, for entities that have more than one.",
                        max_length=100,
                        verbose_name="status field",
                    ),
                ),
                ("total", models.PositiveIntegerField(default=0, verbose_name="total")),
                (
                    "finished",
                    models.PositiveIntegerField(default=0, verbose_name="finished"),
                ),
                (
                    "succeeded",
                    models.PositiveIntegerField(default=0, verbose_name="succeeded"),
                ),
                (
                    "sealed",
                    models.BooleanField(
                        default=False,
                        help_text="No more children will be added, so the total is final. An unsealed batch is never complete, however the numbers look.",
                        verbose_name="sealed",
                    ),
                ),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("joining", "Joining"),
                            ("closed", "Closed"),
                            ("abandoned", "Abandoned"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                        verbose_name="lifecycle",
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        help_text="Short code a guard compares against, e.g. 'timeout'. Deliberately unconstrained: a project records reasons of its own without a migration.",
                        max_length=50,
                        verbose_name="failure reason",
                    ),
                ),
                (
                    "failure_detail",
                    models.TextField(
                        blank=True,
                        help_text="The human half. Nothing branches on this.",
                        verbose_name="failure detail",
                    ),
                ),
                (
                    "timeout_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="timeout at"
                    ),
                ),
                (
                    "joining_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="joining at"
                    ),
                ),
                (
                    "join_retry_after",
                    models.DurationField(
                        blank=True,
                        help_text="Overrides BATCH_JOIN_RETRY_AFTER for this batch. Null uses the setting.",
                        null=True,
                        verbose_name="join retry after",
                    ),
                ),
                (
                    "depth",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="The parent batch's depth plus one. Capped by MAX_BATCH_DEPTH.",
                        verbose_name="depth",
                    ),
                ),
                (
                    "scope_key",
                    models.CharField(
                        blank=True,
                        help_text="Denormalised from the machine that authorised the fan-out.",
                        max_length=255,
                        verbose_name="scope key",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="metadata"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="Snapshotted once, when the batch opens, and reused for every child move. One identity row per fan-out instead of one per child.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.STATE_MACHINES_IDENTITY_MODEL,
                        verbose_name="actor",
                    ),
                ),
                (
                    "join_action",
                    models.ForeignKey(
                        help_text="Fired on the parent for every ending -- clean, partial, total failure and timeout alike. Guards on the edges decide where it lands.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="state_machines.actiontype",
                        verbose_name="join action",
                    ),
                ),
                (
                    "opened_in_status",
                    models.ForeignKey(
                        help_text="The state the record was sitting in when the work was fanned out.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="state_machines.statusdefinition",
                        verbose_name="opened in status",
                    ),
                ),
                (
                    "parent_batch",
                    models.ForeignKey(
                        blank=True,
                        help_text="The batch this one's own parent record is counted by, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_batches",
                        to=settings.STATE_MACHINES_BATCH_MODEL,
                        verbose_name="parent batch",
                    ),
                ),
                (
                    "state_machine_version",
                    models.ForeignKey(
                        help_text="The version that authorised the fan-out, and that the join runs under.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="state_machines.statemachineversion",
                        verbose_name="state machine version",
                    ),
                ),
                (
                    "target_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                        verbose_name="target type",
                    ),
                ),
            ],
            options={
                "verbose_name": "status batch",
                "verbose_name_plural": "status batches",
                "ordering": ("-created_at", "-pk"),
                "abstract": False,
                "swappable": "STATE_MACHINES_BATCH_MODEL",
            },
        ),
        migrations.CreateModel(
            name="StatusBatchReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified at"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Whatever identifies this unit of work to its caller. Must name the work itself, not the attempt: a task id dedupes a retry but not a re-enqueue.",
                        max_length=255,
                        verbose_name="key",
                    ),
                ),
                ("outcome", models.CharField(max_length=20, verbose_name="outcome")),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.STATE_MACHINES_BATCH_MODEL,
                        verbose_name="batch",
                    ),
                ),
            ],
            options={
                "verbose_name": "status batch report",
                "verbose_name_plural": "status batch reports",
                "ordering": ("batch", "pk"),
            },
        ),
        migrations.AddIndex(
            model_name="statusbatch",
            index=models.Index(
                fields=["target_type", "target_id", "status_field"],
                name="statusbatch_target_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="statusbatch",
            index=models.Index(
                fields=["lifecycle", "timeout_at"], name="statusbatch_sweep_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="statusbatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("lifecycle__in", ("open", "joining"))),
                fields=("target_type", "target_id", "status_field"),
                name="statusbatch_one_live_per_record",
            ),
        ),
        migrations.AddConstraint(
            model_name="statusbatchreport",
            constraint=models.UniqueConstraint(
                fields=("batch", "key"), name="statusbatchreport_unique_key_per_batch"
            ),
        ),
    ]
