# Generated by Django 6.1 on 2026-08-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("state_machines", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statemachinetransition",
            name="label_offset_x",
            field=models.IntegerField(
                default=0,
                help_text="Where the edge's card sits relative to the point the canvas would pick for it. Zero keeps it on the edge. Presentation only.",
                verbose_name="label offset x",
            ),
        ),
        migrations.AddField(
            model_name="statemachinetransition",
            name="label_offset_y",
            field=models.IntegerField(
                default=0,
                help_text="Vertical companion to label_offset_x. Presentation only.",
                verbose_name="label offset y",
            ),
        ),
    ]
