# Generated by Django 5.2.17 on 2026-09-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("state_machines", "0002_status_batch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statusbatch",
            name="status_field",
            field=models.CharField(
                default="status_key",
                help_text="The *model field* that is waiting, e.g. 'status_key'. Not the catalog's status_field: this is what the join passes to transition(), and it is what makes a record with two governed statuses able to wait on both at once.",
                max_length=100,
                verbose_name="status field",
            ),
        ),
    ]
