# Generated by Django 6.1 on 2026-08-25 01:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("state_machines", "0002_transition_label_offset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # Both scope foreign keys are declared against STATE_MACHINES_SCOPE_MODEL, so a
        # project that swaps it must have its own tenant table in place first. Without
        # this the autodetector orders the two apps by chance and AddField cannot
        # resolve the target. Unswapped it points back at this app and is a no-op.
        migrations.swappable_dependency(settings.STATE_MACHINES_SCOPE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StateMachineScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified at"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Stable key, e.g. 'org.acme'. Travels with an exported machine.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z0-9][a-z0-9._-]*$",
                                "Keys are stable identifiers: use lowercase letters, digits, '.', '_' and '-'.",
                            )
                        ],
                        verbose_name="key",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=200, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "state machine scope",
                "verbose_name_plural": "state machine scopes",
                "ordering": ("key",),
                "swappable": "STATE_MACHINES_SCOPE_MODEL",
            },
        ),
        migrations.RemoveConstraint(
            model_name="statemachine",
            name="statemachine_one_per_entity_field",
        ),
        migrations.AlterField(
            model_name="statemachine",
            name="key",
            field=models.CharField(
                db_index=True,
                help_text="Stable key referenced from model fields, e.g. 'risk.status'.",
                max_length=150,
                verbose_name="key",
            ),
        ),
        migrations.AddField(
            model_name="statemachine",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                help_text="The tenant this machine is specific to. Null means it is the global machine, used by every tenant that has not been given its own.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="state_machines",
                to=settings.STATE_MACHINES_SCOPE_MODEL,
                verbose_name="scope",
            ),
        ),
        migrations.AddField(
            model_name="statustransition",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                help_text="Denormalised from the machine that authorised the move, so a tenant's history is one indexed filter away. Null for global machines.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.STATE_MACHINES_SCOPE_MODEL,
                verbose_name="scope",
            ),
        ),
        migrations.AddIndex(
            model_name="statustransition",
            index=models.Index(
                fields=["scope", "-created_at"], name="statustransition_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="statemachine",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope__isnull", False)),
                fields=("key", "scope"),
                name="statemachine_unique_key_per_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="statemachine",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope__isnull", True)),
                fields=("key",),
                name="statemachine_unique_global_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="statemachine",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope__isnull", False)),
                fields=("entity_type", "status_field", "scope"),
                name="statemachine_one_per_entity_field_per_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="statemachine",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope__isnull", True)),
                fields=("entity_type", "status_field"),
                name="statemachine_one_global_per_entity_field",
            ),
        ),
    ]
