# Generated by Django 5.2.17 on 2026-09-03 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("state_machines", "0003_batch_status_field_semantics"),
    ]

    operations = [
        migrations.AddField(
            model_name="statemachinestate",
            name="batch_timeout",
            field=models.DurationField(
                blank=True,
                help_text="How long the work may take before the batch gives up on it.",
                null=True,
                verbose_name="batch timeout",
            ),
        ),
        migrations.AddField(
            model_name="statemachinestate",
            name="child_machine",
            field=models.CharField(
                blank=True,
                help_text="Key of the machine the children are governed by. Presentation only: it is what the canvas links to, and nothing resolves it at runtime.",
                max_length=150,
                verbose_name="child machine",
            ),
        ),
        migrations.AddField(
            model_name="statemachinestate",
            name="is_waiting",
            field=models.BooleanField(
                default=False,
                help_text="Entering this state fans work out, and the record waits for it.",
                verbose_name="is waiting",
            ),
        ),
        migrations.AddField(
            model_name="statemachinestate",
            name="join_action",
            field=models.ForeignKey(
                blank=True,
                help_text="Fired on this record for every ending of the batch -- clean, partial, total failure and timeout alike. Guards on the edges decide where it lands.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="state_machines.actiontype",
                verbose_name="join action",
            ),
        ),
    ]
