# Generated by Django 5.2.17 on 2026-09-04 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("state_machines", "0004_state_fan_out"),
    ]

    operations = [
        migrations.AddField(
            model_name="statemachinehook",
            name="record_runs",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "Nothing"),
                    ("failures", "Only failures"),
                    ("all", "Every run"),
                ],
                help_text="Override RECORD_SIDE_EFFECT_RUNS for this binding alone. Blank follows the setting, which is what almost every hook should do.",
                max_length=10,
                verbose_name="record runs",
            ),
        ),
        migrations.CreateModel(
            name="ScopeCapabilityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified at"
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        choices=[
                            ("side_effect", "Side effect"),
                            ("action", "Action / trigger"),
                            ("guard", "Guard"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="resource",
                    ),
                ),
                (
                    "effect",
                    models.CharField(
                        choices=[("allow", "Allow"), ("deny", "Deny")],
                        max_length=10,
                        verbose_name="effect",
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        help_text="An exact key, or a glob over one: 'billing.*' covers every key in that namespace. Matched with fnmatch, so '?' and '[abc]' work too.",
                        max_length=200,
                        verbose_name="pattern",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Why this rule exists. Shown to whoever hits it while authoring.",
                        verbose_name="reason",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who wrote this rule, as they were at the time.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_capability_rules",
                        to=settings.STATE_MACHINES_IDENTITY_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        help_text="The tenant this rule constrains. Rules on the global scope constrain every tenant, including those with rules of their own.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capability_rules",
                        to=settings.STATE_MACHINES_SCOPE_MODEL,
                        verbose_name="scope",
                    ),
                ),
            ],
            options={
                "verbose_name": "scope capability rule",
                "verbose_name_plural": "scope capability rules",
                "ordering": ("scope", "resource", "effect", "pattern"),
                "permissions": [
                    (
                        "bypass_capability_policy",
                        "Can wire up side effects, actions and guards a scope's policy forbids",
                    )
                ],
                "indexes": [
                    models.Index(
                        fields=["scope", "resource"], name="capabilityrule_lookup_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "resource", "effect", "pattern"),
                        name="scopecapabilityrule_unique_pattern",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SideEffectRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified at"
                    ),
                ),
                (
                    "handler_key",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="handler key"
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="target id"
                    ),
                ),
                (
                    "scope_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="scope key"
                    ),
                ),
                (
                    "status_field",
                    models.CharField(
                        default="status", max_length=100, verbose_name="status field"
                    ),
                ),
                (
                    "from_status_key",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="from status key"
                    ),
                ),
                (
                    "to_status_key",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="to status key"
                    ),
                ),
                (
                    "action_key",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="action key"
                    ),
                ),
                (
                    "timing",
                    models.CharField(
                        choices=[("before", "Before"), ("after", "After")],
                        max_length=10,
                        verbose_name="timing",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("transition", "A specific transition"),
                            ("any_transition", "Any transition of the version"),
                            ("enter_state", "Entering a specific state"),
                            ("leave_state", "Leaving a specific state"),
                        ],
                        max_length=20,
                        verbose_name="event",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(db_index=True, verbose_name="started at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Measured on a monotonic clock, not by subtracting the two stamps.",
                        null=True,
                        verbose_name="duration (ms)",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("aborted", "Aborted the transition"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                        verbose_name="outcome",
                    ),
                ),
                (
                    "error_class",
                    models.CharField(
                        blank=True,
                        help_text="Qualified name of the exception, which carries no payload.",
                        max_length=200,
                        verbose_name="error class",
                    ),
                ),
                (
                    "error_detail",
                    models.TextField(
                        blank=True,
                        help_text="The exception's message, truncated. Empty unless CAPTURE_SIDE_EFFECT_ERROR_DETAIL is on: an exception string routinely quotes the value that broke it.",
                        verbose_name="error detail",
                    ),
                ),
                (
                    "hook",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="state_machines.statemachinehook",
                        verbose_name="hook",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.STATE_MACHINES_SCOPE_MODEL,
                        verbose_name="scope",
                    ),
                ),
                (
                    "state_machine_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="side_effect_runs",
                        to="state_machines.statemachineversion",
                        verbose_name="state machine version",
                    ),
                ),
                (
                    "status_transition",
                    models.ForeignKey(
                        blank=True,
                        help_text="The history row of the move this run belongs to. Set for 'before' handlers too, even though that row did not exist while they ran: the link is written at the end, and it is the same move. Null only when the move never committed, which is what a failed run looks like.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="side_effect_runs",
                        to="state_machines.statustransition",
                        verbose_name="status transition",
                    ),
                ),
                (
                    "target_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="side_effect_runs",
                        to="contenttypes.contenttype",
                        verbose_name="target type",
                    ),
                ),
            ],
            options={
                "verbose_name": "side effect run",
                "verbose_name_plural": "side effect runs",
                "ordering": ("-started_at", "-pk"),
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id", "-started_at"],
                        name="sideeffectrun_target_idx",
                    ),
                    models.Index(
                        fields=["scope_key", "-started_at"],
                        name="sideeffectrun_scope_idx",
                    ),
                    models.Index(
                        fields=["handler_key", "outcome", "-started_at"],
                        name="sideeffectrun_handler_idx",
                    ),
                ],
            },
        ),
    ]
